#!/usr/bin/env bash
set -e

# clear LDFLAGS to prevent duplicate ld script linkage (shlelf.xc)
export LDFLAGS=""

exec cmake -DCMAKE_TOOLCHAIN_FILE=/opt/pacbrew/dc/target/sh-elf/usr/lib/cmake/dc-toolchain.cmake "$@"

